FROM quay.io/stewhite/ubi9-cuda-py:0.1.1-devel as vllm-install

WORKDIR /opt/app-root/src

USER 1001

COPY --chown=1001:0 requirements-vllm-0.5.5.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt && \
    rm -f requirements.txt && \
    # Correction for FIPS mode \
    sed -i s/md5/sha1/g /opt/app-root/lib64/python3.11/site-packages/triton/runtime/jit.py

# Fix permissions to support pip in Openshift environments
USER 0
RUN chmod -R g+w /opt/app-root/lib/python3.11/site-packages && \
    fix-permissions /opt/app-root -P
USER 1001


##################
# vLLM container #
##################

FROM quay.io/stewhite/ubi9-cuda-py:0.1.1 as runtime-container

WORKDIR /opt/app-root/src

COPY --from=vllm-install --chown=1001:0 /opt/app-root/lib64 /opt/app-root/lib64
COPY --from=vllm-install --chown=1001:0 /opt/app-root/bin /opt/app-root/bin

USER 1001

EXPOSE 8000

ENTRYPOINT ["python3", "-m", "vllm.entrypoints.openai.api_server"]

